### ISSUE TITLE
What do I do next?

### ISSUE THREAD

**Issue by captnbli** [ovidiub13/agilefant-docker#1]
Despite everything, I have got this thing running on a DO droplet running Debian (because that's what I use every day). 

I am facing a login screen now. What do I enter? If I dragged through the source, I can find it. Why not put it in the readme?

**Comment by ovidiub13** [comment]
Hello. 

I didn't add it in the Readme, because it's in the install/set-up documentation of Agilefant. And IMO anyone setting up Agilefant should check that. 

Anyway default username: admin
Default password: secret

**Comment by captnbli** [comment]
Thanks, I hear you. I was already referencing several sources to set up Docker, Compose, etc, and I really didn't want another one.

If I was doing this for production, I really would use something that curled a script to run as root - it's an all too common hack. I might try to create a Snap package or similar.

Thanks again, Pete
